Repository UBC-MDS/dsci-522-group-23, pull requests merged in 2024-12, with the labels that each got.

#43 docker and environment update
  Dockerfile
  conda-linux-64.lock
  environment.yml
  notebooks/student_performance_predictor_report.ipynb
Labels: feature

#49 qmd file, references.bib, and html export related files
  notebooks/report.html
  notebooks/report.qmd
  notebooks/report_files/figure-html/cell-10-output-2.png
  notebooks/report_files/figure-html/cell-12-output-2.png
  notebooks/report_files/figure-html/cell-18-output-1.png
  notebooks/report_files/figure-html/cell-34-output-1.png
  notebooks/report_files/figure-html/cell-9-output-2.png
  notebooks/report_files/libs/bootstrap/bootstrap-icons.css
  notebooks/report_files/libs/bootstrap/bootstrap-icons.woff
  notebooks/report_files/libs/bootstrap/bootstrap.min.css
  notebooks/report_files/libs/bootstrap/bootstrap.min.js
  notebooks/report_files/libs/clipboard/clipboard.min.js
  notebooks/report_files/libs/quarto-html/anchor.min.js
  notebooks/report_files/libs/quarto-html/popper.min.js
  notebooks/report_files/libs/quarto-html/quarto-syntax-highlighting.css
  notebooks/report_files/libs/quarto-html/quarto.js
  notebooks/report_files/libs/quarto-html/tippy.css
  notebooks/report_files/libs/quarto-html/tippy.umd.min.js
Labels: documentation, feature

#56 replace eda
  notebooks/report.html
  notebooks/report.qmd
  notebooks/report_files/figure-html/cell-10-output-2.png
  notebooks/report_files/figure-html/cell-11-output-1.png
  notebooks/report_files/figure-html/cell-12-output-2.png
  notebooks/report_files/figure-html/cell-18-output-1.png
  notebooks/report_files/figure-html/cell-34-output-1.png
  notebooks/report_files/figure-html/cell-9-output-2.png
  notebooks/report_files/libs/bootstrap/bootstrap-icons.css
  notebooks/report_files/libs/bootstrap/bootstrap-icons.woff
  notebooks/report_files/libs/bootstrap/bootstrap.min.css
  notebooks/report_files/libs/bootstrap/bootstrap.min.js
  notebooks/report_files/libs/clipboard/clipboard.min.js
  notebooks/report_files/libs/quarto-html/anchor.min.js
  notebooks/report_files/libs/quarto-html/popper.min.js
  notebooks/report_files/libs/quarto-html/quarto-syntax-highlighting.css
  notebooks/report_files/libs/quarto-html/quarto.js
  notebooks/report_files/libs/quarto-html/tippy.css
  notebooks/report_files/libs/quarto-html/tippy.umd.min.js
Labels: feature

#69 created preprocessor function and its test
  scripts/download_data.py
  src/download_data.py
  src/preprocessor.py
  tests/test_preprocessor.py
Labels: enhancement
